#!/usr/local/bin/python3

from transcoding_policies.transcoding_policy import TranscodingPolicy
from transcoding_policies.implementations.naive import Naive
from transcoding_policies.implementations.decommission_and_transition import Decommission
from transcoding_policies.implementations.naive_with_intra_batch_reads import NaiveWithIntraBatchReads